CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE ceps_diego (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CepCode" text NOT NULL,
    "Logradouro" text,
    "Bairro" text,
    "Cidade" text,
    "Estado" text,
    CONSTRAINT "PK_ceps_diego" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250429050751_InitialCreate', '9.0.4');

COMMIT;

